version: '3'
services:
  companies:
    build: './companies.microservice'
    ports:
      - "8080:8080"
    depends_on: 
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo/business
  
  mongo:
    image: mongo
    ports:
      - "27017:27017"

